#-------------------------------
# General Site Settings

menu:
- {name: 'About',    url: ''}
- {name: 'Projects', url: 'projects'}
- {name: 'Resume', url: 'resume'}

#-------------------------------
# Projects Section

projects:
- {name: 'Ivorfall', role: 'Lead Gameplay Programmer', url: 'ivorfall'}
- {name: 'Goom', role: 'Gameplay Programmer', url: 'goom'}
- {name: 'Project Eon', role: 'Gameplay Programmer', url: 'projecteon'}

#-------------------------------
# Contact Section

social:
- {icon: 'github',    link: 'https://github.com/Gertew'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/william-nguyen-858476292'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
